tweak sources to compile on JDK 9+
Problem

compilation errors on JDK 9+, for example:

[error] /Users/tisue/twitter-util/util-core/src/main/scala/com/twitter/io/Buf.scala:873:25: ambiguous reference to overloaded definition,
[error] both method position in class ByteBuffer of type (x$1: Int)java.nio.ByteBuffer
[error] and  method position in class Buffer of type ()Int
[error] match expected type ?
[error]         val limit = dup.position + math.min(until, length)
[error]                         ^

this came up in the Scala 2.12 community build

the cause is that the Java folks added some new overloads that scalac
considers ambiguous

Solution

disambiguate by explicitly supplying a single empty argument list

Result

* downstream projects in the Scala community build become unblocked,
  improving test coverage of Scala itself
* twitter-util becomes better prepared for that eventual far-off day
  when it is built on JDK 11 instead of JDK 8